export const images = {
  cart: require("/public/product-images/cart.svg"),
  exchange: require("/public/product-images/exchange.svg"),
  like: require("/public/product-images/like.svg"),
  ring2: require("/public/product-images/ring2.png"),
  ringPlayButton: require("/public/product-images/ringPlayButton.svg"),
  ring3: require("/public/product-images/ringProduct.png"),
  ring4: require("/public/product-images/ring4.png"),
  shipping: require("/public/product-images/shipping.svg"),
  suggested1: require("/public/product-images/suggested1.png"),
  suggested2: require("/public/product-images/suggested2.png"),
  suggested3: require("/public/product-images/suggested3.png"),
  suggested4: require("/public/product-images/suggested4.png"),
  trusted: require("/public/product-images/trusted.svg"),
  warranty: require("/public/product-images/warranty.svg"),
  orderConfirm: require("/public/product-images/orderConfirm.png"),
  orderConfirmHeader: require("/public/product-images/orderConfirmHeader.svg"),
  orderConfirmTitle: require("/public/product-images/orderConfirmTitle.svg"),
};
